version: "3.8"

services:
  # Our actual docker file, which in our case contains our PHP app.
  app:
    build: .
    working_dir: "/var/www/"
    depends_on:
      - "db"
    volumes:
      - "./devops/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
      - "./devops/php/php.ini-development:/usr/local/etc/php/php.ini:ro"
      - "./src:/var/www:cached"
    user: "www-data"
    env_file:
      - "./.env"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Our pgsql database.
  db:
    image: "postgres:15.3-alpine"
    environment:
      POSTGRES_DB: "docker"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "docker"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "./devops/data/postgres:/var/lib/postgresql/data:delegated"

  # Nginx, which is our HTTP server (it sends PHP files to the 'app' service to be processed)
  nginx:
    image: "nginx:alpine"
    depends_on:
      - "app"
    ports:
      - "8080:80"
    volumes:
      - "./src:/var/www:cached"
      - "./devops/nginx/conf.d/:/etc/nginx/conf.d/:ro"
